runtime: python39
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  DB_NAME: "group14kroger"
  INSTANCE_CONNECTION_NAME:  "group14kroger:us-west2:group14kroger"

handlers:
- url: /static
  static_dir: static
- url: /.*
  script: auto

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6